name: build_wheels
run-name: ${{ github.actor }} is building wheels
on: [push]
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
  
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup pip
        run: |
           python -m pip install --upgrade pip
           python -m pip install cibuildwheel==1.6.4
         
      - name:  Install
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get update
                    sudo apt-get install gcc g++
               fi
        shell: bash

      - name: Macos clang
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer
          fi

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
